### ISSUE TITLE
Les encagés - Remontée de soucis de textes

### ISSUE THREAD

**Issue by DjLeChuck** [12-Monkeys-Developers/feedback#1]
Hello,

Voici quelques soucis remontés jusqu'à présent :
 
### De manière général
* Il manque l'utilisation de majuscules accentuées (É, À principalement, mais peut-être d'autre pas encore détectées)
  - La recherche de `\. [éèà]` dans tous les textes permettra de couvrir pas mal de cas
* Il manque l'utilisation de majuscules après l'utilisation de `...`
  - La recherche de `\.\.\. [a-z]` dans tous les textes permettra normalement de gérer tous les cas

### Section 3 - Dans le camp de la loi
 * Quelques notions de base
   - maîtres-chiens : `[...] avec barrages routiers, maîtreschiens, hélicoptères et quadrillage [...]`
* Les PNJ
  - Formulation à revoir : `[...] parmi les dix pages du trombinoscope présent dans la boîte.`
    - Comme on est sur un module Foundry, mettre par exemple : dans ce journal et parmis les différents journaux de PNJ du module.
* La brigade départementale
  - eux-mêmes : `[...] ne font pas les choses euxmêmes, ils courent le risque [...]`
  - porte-à-porte : `[...] Lorsqu'ils ont besoin de porteà-porte [...]`
  - Utiliser un `.` : `[...] mauvaises dépend de vos besoins;`
* Le PSIG
  - eux-mêmes : `[...]  tout à fait procéder euxmêmes, mais quand il faut [...]`

**Comment by Qaw** [comment]
Dans le texte d'origine, il n'y a pas de majuscule après ... 
Tout le reste sera corrigé en 1.0.1
